#%RAML 1.0 DocumentationItem
title: Retail API
content: |
   **Automated inventory system API** This project is used mainly for Retail stores to maintain the  details of Retail store such as stock and account. This Retail shop management software is so designed as to ease the work load ofRetail shop professionals. The main feature includes inventory and stock control, accounting, client management it can be used by a wide variety of outlets (Retailers and Wholesalers) to automate the process of manuallymaintainingtherecordsrelatedtothesubject of maintaining thestockand Bill flows. This project is basically updating the manual chemist inventory System To Automated inventory system, So that organization can manage their record in efficient and organized form. 4. This software helps you to track all the products of Retail shop moreover it’s a Retail shop accounting software. Flexible