#%RAML 1.0 NamedExample
Bills:
 - id: 1452
   noOfItems: 10
   totalCost: "5%"
   totalTax: "20%"
   totalValue: "10%"

 - id: 1453
   noOfItems: 25
   totalCost: "10%"
   totalTax: "10%"
   totalValue: "20%"

 - id: 1454
   noOfItems: 30
   totalCost: "25%"
   totalTax: "15%"
   totalValue: "30%"

 - id: 1455
   noOfItems: 35
   totalCost: "35%"
   totalTax: "20%"
   totalValue: "30%"