#%RAML 1.0 NamedExample
Products:
 - id: 10
   name: "orange juce"
   barcode: "Or12"
   rate: 2
   productCategory: "organic"

 - id: 11
   name: "Banana"
   barcode: "Ba26"
   rate: 9
   productCategory: "organic"

 - id: 12
   name: "Sugar"
   barcode: "Su52"
   rate: 6
   productCategory: "Nonorganic"

 - id: 13
   name: "Egge"
   barcode: "Eg15"
   rate: 5
   productCategory: "Nonorganic"